// frontend/src/app/features/enterprise/employees/employees.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import {
  EnterpriseService,
  EnterpriseEmployee,
  EmployeeAssignment,
  EnterpriseInvite,
} from '../../../core/services/enterprise.service';
import {
  EmployeeDetailPanelComponent,
  EmployeeDetailDialogResult,
} from './employee-detail-panel.component';

const ROLE_LABELS: Record<string, string> = {
  agent: 'Agent terrain',
  manager: 'Manager',
  admin: 'Administrateur',
  hr: 'Ressources humaines',
  accountant: 'Comptable',
};

type EmployeeFilter = 'all' | 'active' | 'inactive';
type PageTab = 'employees' | 'assignments';

@Component({
  selector: 'app-enterprise-employees',
  standalone: true,
  imports: [
    CommonModule, FormsModule, RouterModule,
    MatCardModule, MatButtonModule, MatIconModule, MatChipsModule,
    MatProgressSpinnerModule, MatSnackBarModule, MatDialogModule,
  ],
  template: `
    <div class="page-container">
      <div class="page-header">
        <div>
          <h1><mat-icon>people</mat-icon> Employés</h1>
          <p>{{ activeCount }} actif(s) · {{ employees.length }} au total</p>
        </div>
        <div class="header-actions" *ngIf="pageTab === 'employees'">
          <button mat-stroked-button (click)="openInviteForm()">
            <mat-icon>mail_outline</mat-icon> Inviter un prestataire
          </button>
          <a mat-stroked-button routerLink="/enterprise/invitations">
            <mat-icon>history</mat-icon> Historique invitations
          </a>
          <a mat-stroked-button routerLink="/enterprise/appels">
            <mat-icon>campaign</mat-icon> Appels à candidature
          </a>
          <button mat-raised-button color="primary" (click)="openCreateForm()">
            <mat-icon>person_add</mat-icon> Nouvel employé
          </button>
        </div>
      </div>

      <nav class="page-tabs">
        <button mat-stroked-button [class.active]="pageTab === 'employees'" (click)="pageTab = 'employees'">
          Liste des employés
        </button>
        <button mat-stroked-button [class.active]="pageTab === 'assignments'" (click)="pageTab = 'assignments'">
          Affectations ({{ assignments.length }})
        </button>
      </nav>

      <ng-container *ngIf="pageTab === 'employees'">
        <div class="filters">
          <button mat-stroked-button [color]="filter === 'all' ? 'primary' : undefined" (click)="filter = 'all'">Tous</button>
          <button mat-stroked-button [color]="filter === 'active' ? 'primary' : undefined" (click)="filter = 'active'">Actifs</button>
          <button mat-stroked-button [color]="filter === 'inactive' ? 'primary' : undefined" (click)="filter = 'inactive'">Inactifs</button>
          <button mat-stroked-button (click)="load()"><mat-icon>refresh</mat-icon> Actualiser</button>
        </div>

        <mat-card *ngIf="pendingInvites.length" class="invites-card">
          <h3>Invitations en attente ({{ pendingInvites.length }})</h3>
          <div class="invite-row" *ngFor="let inv of pendingInvites">
            <div class="invite-info">
              <strong>{{ inv.email }}</strong>
              <span class="meta">{{ roleLabel(inv.role) }} · {{ inv.position || '—' }}</span>
              <span class="meta" *ngIf="inv.created_at">Envoyée le {{ inv.created_at | date:'short' }}</span>
            </div>
            <button mat-stroked-button color="warn" (click)="cancelInvite(inv)" [disabled]="cancellingInviteId === inv.id">
              Annuler
            </button>
          </div>
        </mat-card>

        <mat-card *ngIf="showInviteForm" class="form-card">
          <h3>Inviter un prestataire</h3>
          <p class="form-hint">Pour un compte existant sur BlockTask — il recevra une invitation à rejoindre votre entreprise.</p>
          <div class="form-grid">
            <input class="field" [(ngModel)]="inviteForm.email" placeholder="Email *" type="email" />
            <input class="field" [(ngModel)]="inviteForm.position" placeholder="Poste" />
            <select class="field" [(ngModel)]="inviteForm.role">
              <option value="agent">Agent terrain</option>
              <option value="manager">Manager</option>
              <option value="admin">Administrateur</option>
              <option value="hr">Ressources humaines</option>
              <option value="accountant">Comptable</option>
            </select>
          </div>
          <textarea class="field message-field" [(ngModel)]="inviteForm.message" placeholder="Message optionnel" rows="2"></textarea>
          <div class="form-actions">
            <button mat-button (click)="cancelInviteForm()">Annuler</button>
            <button mat-raised-button color="primary" (click)="submitInvite()" [disabled]="inviting">
              {{ inviting ? 'Envoi...' : "Envoyer l'invitation" }}
            </button>
          </div>
        </mat-card>

        <mat-card *ngIf="showForm" class="form-card">
          <h3>Nouvel employé</h3>
          <div class="form-grid">
            <input class="field" [(ngModel)]="form.first_name" placeholder="Prénom *" />
            <input class="field" [(ngModel)]="form.last_name" placeholder="Nom *" />
            <input class="field" [(ngModel)]="form.email" placeholder="Email *" />
            <input class="field" [(ngModel)]="form.phone" placeholder="Téléphone" />
            <input class="field" [(ngModel)]="form.position" placeholder="Poste" />
            <select class="field" [(ngModel)]="form.role">
              <option value="agent">Agent terrain</option>
              <option value="manager">Manager</option>
              <option value="admin">Administrateur</option>
              <option value="hr">Ressources humaines</option>
              <option value="accountant">Comptable</option>
            </select>
          </div>
          <div class="form-actions">
            <button mat-button (click)="cancelForm()">Annuler</button>
            <button mat-raised-button color="primary" (click)="saveEmployee()" [disabled]="saving">
              {{ saving ? 'Enregistrement...' : 'Créer le compte' }}
            </button>
          </div>
        </mat-card>

        <div class="loading" *ngIf="loading"><mat-spinner diameter="36"></mat-spinner></div>

        <div class="emp-grid" *ngIf="!loading">
          <mat-card class="emp-card clickable" *ngFor="let e of filteredEmployees"
            [class.selected]="selectedId === e.id" (click)="openEmployeePanel(e)">
            <div class="emp-avatar">{{ e.first_name[0] }}{{ e.last_name[0] }}</div>
            <div class="emp-info">
              <h3>{{ e.first_name }} {{ e.last_name }}</h3>
              <p>{{ e.position || roleLabel(e.role) }} · {{ e.email }}</p>
              <span class="missions">{{ e.missions_completed }} mission(s) terminée(s)</span>
            </div>
            <mat-chip [class]="e.is_active ? 'active' : 'inactive'">{{ e.is_active ? 'Actif' : 'Inactif' }}</mat-chip>
          </mat-card>
          <p class="empty" *ngIf="!filteredEmployees.length">Aucun employé pour ce filtre</p>
        </div>
      </ng-container>

      <ng-container *ngIf="pageTab === 'assignments'">
        <div class="loading" *ngIf="loading"><mat-spinner diameter="36"></mat-spinner></div>
        <div class="mission-list" *ngIf="!loading">
          <mat-card class="mission-card" *ngFor="let a of assignments">
            <div>
              <h3>{{ a.mission_title || ('Mission ' + (a.mission | slice:0:8)) }}</h3>
              <span class="meta">Employé : {{ a.employee_name || '—' }} · {{ a.assigned_at | date:'short' }}</span>
            </div>
            <mat-chip>{{ assignmentLabel(a.assignment_status) }}</mat-chip>
          </mat-card>
          <p class="empty" *ngIf="!assignments.length">Aucune affectation — assignez un employé depuis une mission reçue</p>
        </div>
      </ng-container>
    </div>
  `,
  styles: [`
    .page-container { max-width: 1100px; margin: 0 auto; }
    .page-header { display: flex; justify-content: space-between; margin-bottom: 16px; flex-wrap: wrap; gap: 12px;
      h1 { margin: 0 0 4px; display: flex; align-items: center; gap: 8px; font-size: 22px; }
      p { margin: 0; color: #6b7280; font-size: 14px; }
    }
    .header-actions { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; }
    .invites-card { padding: 20px; margin-bottom: 20px;
      h3 { margin: 0 0 12px; font-size: 16px; }
    }
    .invite-row { display: flex; justify-content: space-between; align-items: center; gap: 12px; padding: 12px 0; border-bottom: 1px solid #f3f4f6;
      &:last-child { border-bottom: none; }
    }
    .invite-info { display: flex; flex-direction: column; gap: 2px;
      .meta { font-size: 12px; color: #6b7280; }
    }
    .form-hint { margin: 0 0 12px; font-size: 13px; color: #6b7280; }
    .message-field { width: 100%; margin-bottom: 12px; resize: vertical; box-sizing: border-box; }
    .page-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }
    .page-tabs button.active { border-color: #2e7d32; color: #2e7d32; }
    .filters { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 16px; }
    .form-card { padding: 20px; margin-bottom: 20px;
      h3 { margin: 0 0 12px; font-size: 16px; }
    }
    .form-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 12px; }
    .field { padding: 10px 12px; border: 1px solid #d1d5db; border-radius: 8px; font-size: 14px; }
    .form-actions { display: flex; justify-content: flex-end; gap: 8px; }
    .loading { display: flex; justify-content: center; padding: 40px; }
    .emp-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); gap: 16px; }
    .emp-card { padding: 20px; display: flex; align-items: flex-start; gap: 16px; }
    .emp-card.clickable { cursor: pointer; transition: box-shadow 0.15s, border-color 0.15s; border: 2px solid transparent; }
    .emp-card.clickable:hover { box-shadow: 0 4px 14px rgba(0,0,0,0.08); }
    .emp-card.selected { border-color: #3CB371; box-shadow: 0 4px 14px rgba(60,179,113,0.15); }
    mat-chip.active { background: #d1fae5 !important; color: #065f46 !important; }
    mat-chip.inactive { background: #f3f4f6 !important; color: #6b7280 !important; }
    .emp-avatar { width: 48px; height: 48px; border-radius: 50%; background: #3CB371; color: #fff; display: flex; align-items: center; justify-content: center; font-weight: 700; flex-shrink: 0; }
    .emp-info { flex: 1; min-width: 0;
      h3 { margin: 0 0 4px; font-size: 16px; }
      p { margin: 0; font-size: 13px; color: #6b7280; }
      .missions { display: block; font-size: 12px; color: #9ca3af; margin-top: 4px; }
    }
    .mission-card { padding: 16px 20px; display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; gap: 12px;
      h3 { margin: 0 0 4px; font-size: 15px; } .meta { font-size: 12px; color: #9ca3af; }
    }
    .empty { grid-column: 1 / -1; text-align: center; color: #9ca3af; padding: 40px; }
    @media (max-width: 768px) { .form-grid { grid-template-columns: 1fr; } .emp-card { flex-direction: column; } }
  `],
})
export class EnterpriseEmployeesComponent implements OnInit {
  employees: EnterpriseEmployee[] = [];
  assignments: EmployeeAssignment[] = [];
  loading = true;
  saving = false;
  showForm = false;
  showInviteForm = false;
  inviting = false;
  cancellingInviteId: string | null = null;
  pendingInvites: EnterpriseInvite[] = [];
  selectedId: string | null = null;
  filter: EmployeeFilter = 'all';
  pageTab: PageTab = 'employees';
  form = { first_name: '', last_name: '', email: '', phone: '', position: '', role: 'agent' };
  inviteForm = { email: '', role: 'agent', position: '', message: '' };

  constructor(
    private enterpriseService: EnterpriseService,
    private snack: MatSnackBar,
    private dialog: MatDialog,
  ) {}

  ngOnInit(): void { this.load(); }

  get activeCount(): number {
    return this.employees.filter((e) => e.is_active).length;
  }

  get filteredEmployees(): EnterpriseEmployee[] {
    if (this.filter === 'active') return this.employees.filter((e) => e.is_active);
    if (this.filter === 'inactive') return this.employees.filter((e) => !e.is_active);
    return this.employees;
  }

  roleLabel(role: string): string {
    return ROLE_LABELS[role] || role;
  }

  assignmentLabel(s?: string): string {
    const m: Record<string, string> = {
      pending: 'En attente', accepted: 'Confirmée', rejected: 'Refusée', completed: 'Terminée',
    };
    return m[s || ''] || s || '—';
  }

  load(): void {
    this.loading = true;
    this.enterpriseService.getEmployees().subscribe({
      next: (e) => { this.employees = e; },
    });
    this.enterpriseService.getAssignments().subscribe({
      next: (a) => { this.assignments = a; this.loading = false; },
      error: () => { this.loading = false; },
    });
    this.enterpriseService.listEnterpriseInvites('pending').subscribe({
      next: (invites) => { this.pendingInvites = invites; },
    });
  }

  openCreateForm(): void {
    this.selectedId = null;
    this.showInviteForm = false;
    this.form = { first_name: '', last_name: '', email: '', phone: '', position: '', role: 'agent' };
    this.showForm = true;
  }

  openInviteForm(): void {
    this.selectedId = null;
    this.showForm = false;
    this.inviteForm = { email: '', role: 'agent', position: '', message: '' };
    this.showInviteForm = true;
  }

  cancelInviteForm(): void {
    this.showInviteForm = false;
  }

  submitInvite(): void {
    if (!this.inviteForm.email?.trim()) {
      this.snack.open('L\'email est requis', 'Fermer', { duration: 3000 });
      return;
    }
    this.inviting = true;
    this.enterpriseService.inviteProvider({
      email: this.inviteForm.email.trim(),
      role: this.inviteForm.role,
      position: this.inviteForm.position || undefined,
      message: this.inviteForm.message || undefined,
    }).subscribe({
      next: () => {
        this.inviting = false;
        this.snack.open('Invitation envoyée', 'Fermer', { duration: 3000 });
        this.cancelInviteForm();
        this.load();
      },
      error: (err) => {
        this.inviting = false;
        this.snack.open(err.error?.detail || 'Erreur envoi invitation', 'Fermer', { duration: 4000 });
      },
    });
  }

  cancelInvite(inv: EnterpriseInvite): void {
    if (!confirm(`Annuler l'invitation pour ${inv.email} ?`)) return;
    this.cancellingInviteId = inv.id;
    this.enterpriseService.cancelEnterpriseInvite(inv.id).subscribe({
      next: () => {
        this.cancellingInviteId = null;
        this.snack.open('Invitation annulée', 'Fermer', { duration: 3000 });
        this.load();
      },
      error: (err) => {
        this.cancellingInviteId = null;
        this.snack.open(err.error?.detail || 'Erreur', 'Fermer', { duration: 4000 });
      },
    });
  }

  openEmployeePanel(e: EnterpriseEmployee, editing = false): void {
    this.showForm = false;
    this.selectedId = e.id;
    const ref = this.dialog.open(EmployeeDetailPanelComponent, {
      width: '520px',
      maxWidth: '95vw',
      panelClass: 'employee-detail-dialog',
      data: { employee: e, editing },
    });
    ref.afterClosed().subscribe((result?: EmployeeDetailDialogResult) => {
      if (!result || result.action === 'close') return;
      if (result.action === 'save' && result.payload) {
        this.saveEmployeeUpdate(e, result.payload);
      } else if (result.action === 'toggle') {
        this.toggleActive(e);
      } else if (result.action === 'delete') {
        this.removeEmployee(e);
      }
    });
  }

  cancelForm(): void {
    this.showForm = false;
  }

  saveEmployee(): void {
    if (!this.form.first_name || !this.form.last_name || !this.form.email) {
      this.snack.open('Prénom, nom et email sont requis', 'Fermer', { duration: 3000 });
      return;
    }
    this.saving = true;
    this.enterpriseService.createEmployee(this.form).subscribe({
      next: (res) => {
        this.saving = false;
        const msg = res.temporary_password
          ? `Compte créé — mot de passe temporaire : ${res.temporary_password}`
          : 'Employé ajouté';
        this.snack.open(msg, 'Fermer', { duration: res.temporary_password ? 15000 : 3000 });
        this.cancelForm();
        this.load();
      },
      error: (err) => {
        this.saving = false;
        const detail = err.error?.detail || '';
        if (typeof detail === 'string' && detail.toLowerCase().includes('existe déjà')) {
          this.snack.open(
            'Un compte existe déjà avec cet email. Utilisez « Inviter un prestataire » pour l\'ajouter à votre entreprise.',
            'Fermer',
            { duration: 6000 },
          );
        } else {
          this.snack.open(detail || 'Erreur', 'Fermer', { duration: 4000 });
        }
      },
    });
  }

  saveEmployeeUpdate(e: EnterpriseEmployee, payload: Partial<EnterpriseEmployee>): void {
    this.saving = true;
    this.enterpriseService.updateEmployee(e.id, payload).subscribe({
      next: () => {
        this.saving = false;
        this.snack.open('Employé mis à jour', 'Fermer', { duration: 3000 });
        this.load();
      },
      error: (err) => {
        this.saving = false;
        this.snack.open(err.error?.detail || 'Erreur', 'Fermer', { duration: 4000 });
      },
    });
  }

  toggleActive(e: EnterpriseEmployee): void {
    const next = !e.is_active;
    this.enterpriseService.updateEmployee(e.id, { is_active: next }).subscribe({
      next: () => {
        this.snack.open(next ? 'Employé réactivé' : 'Employé désactivé', 'Fermer', { duration: 2500 });
        this.load();
      },
      error: (err) => this.snack.open(err.error?.detail || 'Erreur', 'Fermer', { duration: 4000 }),
    });
  }

  removeEmployee(e: EnterpriseEmployee): void {
    if (!confirm(`Supprimer ${e.first_name} ${e.last_name} ? Le compte sera désactivé.`)) return;
    this.enterpriseService.deactivateEmployee(e.id).subscribe({
      next: () => {
        this.snack.open('Employé supprimé', 'Fermer', { duration: 3000 });
        this.selectedId = null;
        this.load();
      },
      error: (err) => this.snack.open(err.error?.detail || 'Erreur', 'Fermer', { duration: 4000 }),
    });
  }
}

// mobile/app/employees.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import {
  cancelEnterpriseInvite,
  createEmployee,
  getAssignments,
  getEmployees,
  inviteProvider,
  listEnterpriseInvites,
  type EmployeeAssignment,
  type EnterpriseEmployee,
  type EnterpriseInvite,
} from '../src/api/enterprise';
import { PrimaryButton, SecondaryButton, Input } from '../src/components/buttons';
import { Card, Loader } from '../src/components/ui';
import { AppLayout } from '../src/components/layout/AppLayout';
import { PageHeader, SoftCard, TabBar } from '../src/components/widgets';
import { colors, radius, spacing } from '../src/constants/theme';
import { useEnterpriseGuard } from '../src/hooks/useEnterpriseGuard';
import { assignmentStatusLabel } from '../src/utils/enterprise';
import { ApiError } from '../src/api/client';

const ROLE_OPTIONS = [
  { id: 'agent', label: 'Agent terrain' },
  { id: 'manager', label: 'Manager' },
  { id: 'admin', label: 'Administrateur' },
  { id: 'hr', label: 'RH' },
  { id: 'accountant', label: 'Comptable' },
];

const ROLE_LABELS: Record<string, string> = Object.fromEntries(
  ROLE_OPTIONS.map((r) => [r.id, r.label]),
);

type PageTab = 'employees' | 'assignments' | 'invites';
type EmployeeFilter = 'all' | 'active' | 'inactive';

const EMPTY_FORM = {
  first_name: '',
  last_name: '',
  email: '',
  phone: '',
  position: '',
  role: 'agent',
};

const EMPTY_INVITE = {
  email: '',
  position: 'Agent terrain',
  role: 'agent',
  message: '',
};

export default function EmployeesScreen() {
  const { redirect: guardRedirect } = useEnterpriseGuard();
  const [pageTab, setPageTab] = useState<PageTab>('employees');
  const [filter, setFilter] = useState<EmployeeFilter>('all');
  const [employees, setEmployees] = useState<EnterpriseEmployee[]>([]);
  const [assignments, setAssignments] = useState<EmployeeAssignment[]>([]);
  const [pendingInvites, setPendingInvites] = useState<EnterpriseInvite[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [showInviteForm, setShowInviteForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [inviting, setInviting] = useState(false);
  const [form, setForm] = useState(EMPTY_FORM);
  const [inviteForm, setInviteForm] = useState(EMPTY_INVITE);

  const load = useCallback(async () => {
    try {
      const [emps, assigns, invites] = await Promise.all([
        getEmployees(),
        getAssignments(),
        listEnterpriseInvites('pending').catch(() => [] as EnterpriseInvite[]),
      ]);
      setEmployees(emps);
      setAssignments(assigns);
      setPendingInvites(invites);
    } catch {
      setEmployees([]);
      setAssignments([]);
      setPendingInvites([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    setLoading(true);
    load();
  }, [load]);

  const activeCount = useMemo(
    () => employees.filter((e) => e.is_active).length,
    [employees],
  );

  const filtered = useMemo(() => {
    if (filter === 'active') return employees.filter((e) => e.is_active);
    if (filter === 'inactive') return employees.filter((e) => !e.is_active);
    return employees;
  }, [employees, filter]);

  const save = async () => {
    if (!form.first_name || !form.last_name || !form.email) {
      Alert.alert('Champs requis', 'Prénom, nom et email sont obligatoires.');
      return;
    }
    setSaving(true);
    try {
      const res = await createEmployee(form);
      Alert.alert(
        'Employé créé',
        res.temporary_password
          ? `Mot de passe temporaire : ${res.temporary_password}\nCommuniquez-le pour la première connexion.`
          : 'Compte employé créé.',
      );
      setForm(EMPTY_FORM);
      setShowForm(false);
      await load();
    } catch (e) {
      const msg = e instanceof ApiError ? e.message : 'Enregistrement impossible';
      if (/existe déjà/i.test(msg)) {
        Alert.alert(
          'Compte existant',
          'Cet email existe déjà. Utilisez « Inviter » pour lier un prestataire existant.',
        );
      } else {
        Alert.alert('Erreur', msg);
      }
    } finally {
      setSaving(false);
    }
  };

  const sendInvite = async () => {
    if (!inviteForm.email.trim()) {
      Alert.alert('Email requis', 'Saisissez l’email du prestataire à inviter.');
      return;
    }
    setInviting(true);
    try {
      await inviteProvider(inviteForm);
      Alert.alert('Invitation envoyée', 'Le prestataire devra accepter avant d’être lié.');
      setInviteForm(EMPTY_INVITE);
      setShowInviteForm(false);
      setPageTab('invites');
      await load();
    } catch (e) {
      Alert.alert('Erreur', e instanceof ApiError ? e.message : 'Invitation impossible');
    } finally {
      setInviting(false);
    }
  };

  const cancelInvite = async (id: string) => {
    try {
      await cancelEnterpriseInvite(id);
      await load();
    } catch (e) {
      Alert.alert('Erreur', e instanceof ApiError ? e.message : 'Annulation impossible');
    }
  };

  if (guardRedirect) return guardRedirect;

  return (
    <AppLayout
      title="Employés"
      showBack
      refreshing={refreshing}
      onRefresh={() => { setRefreshing(true); load(); }}
    >
      <PageHeader
        title="Employés"
        subtitle={`${activeCount} actif(s) · ${employees.length} au total`}
        action={
          pageTab === 'employees' ? (
            <View style={styles.headerActions}>
              <SecondaryButton
                label={showInviteForm ? 'Fermer' : 'Inviter'}
                onPress={() => {
                  setShowInviteForm((v) => !v);
                  setShowForm(false);
                }}
              />
              <PrimaryButton
                label={showForm ? 'Fermer' : '+ Ajouter'}
                onPress={() => {
                  setShowForm((v) => !v);
                  setShowInviteForm(false);
                }}
              />
            </View>
          ) : undefined
        }
      />

      <TabBar
        value={pageTab}
        onChange={(id) => setPageTab(id as PageTab)}
        tabs={[
          { id: 'employees', label: 'Liste', count: employees.length },
          { id: 'invites', label: 'Invitations', count: pendingInvites.length },
          { id: 'assignments', label: 'Affectations', count: assignments.length },
        ]}
      />

      {pageTab === 'employees' && (
        <>
          <View style={styles.filters}>
            {(['all', 'active', 'inactive'] as EmployeeFilter[]).map((f) => (
              <Pressable
                key={f}
                onPress={() => setFilter(f)}
                style={[styles.filterChip, filter === f && styles.filterChipActive]}
              >
                <Text style={[styles.filterText, filter === f && styles.filterTextActive]}>
                  {f === 'all' ? 'Tous' : f === 'active' ? 'Actifs' : 'Inactifs'}
                </Text>
              </Pressable>
            ))}
          </View>

          {showInviteForm && (
            <SoftCard style={styles.form}>
              <Text style={styles.formTitle}>Inviter un prestataire</Text>
              <Text style={styles.hint}>
                Pour un compte existant : il devra accepter l’invitation avant d’être lié.
              </Text>
              <Input
                placeholder="Email *"
                keyboardType="email-address"
                autoCapitalize="none"
                value={inviteForm.email}
                onChangeText={(v) => setInviteForm({ ...inviteForm, email: v })}
              />
              <Input
                placeholder="Poste"
                value={inviteForm.position}
                onChangeText={(v) => setInviteForm({ ...inviteForm, position: v })}
              />
              <Input
                placeholder="Message (optionnel)"
                value={inviteForm.message}
                onChangeText={(v) => setInviteForm({ ...inviteForm, message: v })}
              />
              <View style={styles.roleRow}>
                {ROLE_OPTIONS.map((r) => (
                  <Pressable
                    key={r.id}
                    onPress={() => setInviteForm({ ...inviteForm, role: r.id })}
                    style={[styles.roleChip, inviteForm.role === r.id && styles.roleChipActive]}
                  >
                    <Text style={[styles.roleText, inviteForm.role === r.id && styles.roleTextActive]}>{r.label}</Text>
                  </Pressable>
                ))}
              </View>
              <View style={styles.formActions}>
                <View style={{ flex: 1 }}>
                  <PrimaryButton label="Envoyer l’invitation" loading={inviting} onPress={sendInvite} />
                </View>
                <View style={{ flex: 1 }}>
                  <SecondaryButton label="Annuler" onPress={() => setShowInviteForm(false)} />
                </View>
              </View>
            </SoftCard>
          )}

          {showForm && (
            <SoftCard style={styles.form}>
              <Text style={styles.formTitle}>Nouvel employé</Text>
              <Input placeholder="Prénom *" value={form.first_name} onChangeText={(v) => setForm({ ...form, first_name: v })} />
              <Input placeholder="Nom *" value={form.last_name} onChangeText={(v) => setForm({ ...form, last_name: v })} />
              <Input
                placeholder="Email *"
                keyboardType="email-address"
                autoCapitalize="none"
                value={form.email}
                onChangeText={(v) => setForm({ ...form, email: v })}
              />
              <Input placeholder="Téléphone" value={form.phone} onChangeText={(v) => setForm({ ...form, phone: v })} />
              <Input placeholder="Poste" value={form.position} onChangeText={(v) => setForm({ ...form, position: v })} />
              <View style={styles.roleRow}>
                {ROLE_OPTIONS.map((r) => (
                  <Pressable
                    key={r.id}
                    onPress={() => setForm({ ...form, role: r.id })}
                    style={[styles.roleChip, form.role === r.id && styles.roleChipActive]}
                  >
                    <Text style={[styles.roleText, form.role === r.id && styles.roleTextActive]}>{r.label}</Text>
                  </Pressable>
                ))}
              </View>
              <View style={styles.formActions}>
                <View style={{ flex: 1 }}>
                  <PrimaryButton label="Créer le compte" loading={saving} onPress={save} />
                </View>
                <View style={{ flex: 1 }}>
                  <SecondaryButton label="Annuler" onPress={() => setShowForm(false)} />
                </View>
              </View>
            </SoftCard>
          )}

          {loading ? (
            <Loader />
          ) : filtered.length === 0 ? (
            <Text style={styles.empty}>Aucun employé pour ce filtre.</Text>
          ) : (
            filtered.map((e) => (
              <Pressable key={e.id} onPress={() => router.push(`/employee/${e.id}`)}>
                <Card style={styles.card}>
                  <View style={styles.avatar}>
                    <Text style={styles.avatarText}>{e.first_name[0]}{e.last_name[0]}</Text>
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={styles.name}>{e.first_name} {e.last_name}</Text>
                    <Text style={styles.meta}>{ROLE_LABELS[e.role] || e.role} · {e.email}</Text>
                    <Text style={styles.meta}>{e.missions_completed ?? 0} mission(s)</Text>
                  </View>
                  <View style={[styles.badge, e.is_active ? styles.active : styles.inactive]}>
                    <Text style={styles.badgeText}>{e.is_active ? 'Actif' : 'Inactif'}</Text>
                  </View>
                  <Text style={styles.chevron}>›</Text>
                </Card>
              </Pressable>
            ))
          )}
        </>
      )}

      {pageTab === 'invites' && (
        loading ? (
          <Loader />
        ) : (
          <>
            <Pressable onPress={() => router.push('/enterprise-invitations')}>
              <Text style={styles.link}>Voir l'historique des invitations →</Text>
            </Pressable>
            <Pressable onPress={() => router.push('/enterprise-appels')}>
              <Text style={styles.link}>Publier un appel à candidature →</Text>
            </Pressable>
            {pendingInvites.length === 0 ? (
              <Text style={styles.empty}>Aucune invitation en attente.</Text>
            ) : (
              pendingInvites.map((inv) => (
                <Card key={inv.id} style={styles.assignCard}>
                  <Text style={styles.name}>{inv.email}</Text>
                  <Text style={styles.meta}>
                    {ROLE_LABELS[inv.role] || inv.role}
                    {inv.position ? ` · ${inv.position}` : ''}
                    {inv.user_exists ? ' · compte existant' : ' · nouvel email'}
                  </Text>
                  {inv.expires_at ? (
                    <Text style={styles.meta}>
                      Expire le {new Date(inv.expires_at).toLocaleDateString('fr-FR')}
                    </Text>
                  ) : null}
                  <View style={styles.formActions}>
                    <View style={{ flex: 1 }}>
                      <SecondaryButton label="Annuler l’invitation" onPress={() => cancelInvite(inv.id)} />
                    </View>
                  </View>
                </Card>
              ))
            )}
          </>
        )
      )}

      {pageTab === 'assignments' && (
        loading ? (
          <Loader />
        ) : assignments.length === 0 ? (
          <Text style={styles.empty}>Aucune affectation pour le moment.</Text>
        ) : (
          assignments.map((a) => (
            <Pressable key={a.id} onPress={() => a.mission && router.push(`/mission/${a.mission}`)}>
              <Card style={styles.assignCard}>
                <Text style={styles.name}>{a.mission_title || 'Mission'}</Text>
                <Text style={styles.meta}>Employé : {a.employee_name || '—'}</Text>
                <Text style={styles.meta}>
                  {assignmentStatusLabel(a.assignment_status)}
                  {a.assigned_at ? ` · ${new Date(a.assigned_at).toLocaleString('fr-FR')}` : ''}
                </Text>
                <Text style={styles.link}>Voir la mission ›</Text>
              </Card>
            </Pressable>
          ))
        )
      )}
    </AppLayout>
  );
}

const styles = StyleSheet.create({
  headerActions: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: spacing.md },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  filterChipActive: { borderColor: colors.primary, backgroundColor: colors.primaryLight },
  filterText: { fontSize: 13, fontWeight: '600', color: colors.text },
  filterTextActive: { color: colors.primary },
  form: { marginBottom: spacing.md, gap: spacing.sm },
  formTitle: { fontWeight: '700', fontSize: 16, color: colors.text, marginBottom: 4 },
  hint: { fontSize: 12, color: colors.textMuted, marginBottom: 4 },
  roleRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  roleChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  roleChipActive: { borderColor: colors.primary, backgroundColor: colors.primaryLight },
  roleText: { fontSize: 11, fontWeight: '600', color: colors.textMuted },
  roleTextActive: { color: colors.primary },
  formActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm },
  empty: { textAlign: 'center', color: colors.textMuted, paddingVertical: spacing.xl },
  card: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.sm },
  assignCard: { marginBottom: spacing.sm },
  avatar: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center',
  },
  avatarText: { color: colors.primary, fontWeight: '800' },
  name: { fontWeight: '700', color: colors.text, fontSize: 15 },
  meta: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999 },
  active: { backgroundColor: '#d1fae5' },
  inactive: { backgroundColor: '#f3f4f6' },
  badgeText: { fontSize: 11, fontWeight: '700', color: colors.text },
  chevron: { fontSize: 22, color: colors.textMuted, fontWeight: '300' },
  link: { color: colors.primary, fontWeight: '700', marginTop: 8, fontSize: 13 },
});
